set eprj_proj_name "artix_dma"
set eprj_def_root "src"
set eprj_top_entity "design_1_wrapper"
set eprj_board_part ""
set eprj_part "xca7200t-ffg1156-2"
set eprj_target_language "VHDL"
set eprj_simulator_language "Mixed"
set eprj_default_lib "xil_defaultlib"
set eprj_synth_flow "Vivado Synthesis 2015"
set eprj_synth_strategy "Flow_PerfOptimized_high"
set eprj_impl_flow "Vivado Implementation 2015"
set eprj_impl_strategy "Performance_Retiming"
set eprj_vivado_version "2015.4"
set eprj_vivado_version_allow_upgrade false

